// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkelhdyulmdhdgerzunu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrZWxoZHl1bG1kaGRnZXJ6dW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwMzIxMTcsImV4cCI6MjA5MjYwODExN30.hDh-GUqgexJVkb5Zqcl6t-OSRNMyQ4it7K6R9jAS9F8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});